import { Course, Sentence } from "@/types/learning";

export const seedCourses: Course[] = [
  {
    _id: "course-office-greeting",
    title: "上班打招呼",
    slug: "office-greeting",
    description: "每天在办公室最常用的寒暄表达。",
    difficulty: "beginner",
    estimatedMinutes: 12,
    category: "职场",
    order: 1,
    isFeatured: true,
    isPublished: true,
  },
  {
    _id: "course-self-intro",
    title: "自我介绍",
    slug: "self-introduction",
    description: "介绍姓名、岗位和工作内容。",
    difficulty: "beginner",
    estimatedMinutes: 14,
    category: "职场",
    order: 2,
    isFeatured: true,
    isPublished: true,
  },
  {
    _id: "course-meeting",
    title: "开会基础表达",
    slug: "meeting-basics",
    description: "会议中提问、确认和补充意见。",
    difficulty: "elementary",
    estimatedMinutes: 16,
    category: "会议",
    order: 3,
    isFeatured: true,
    isPublished: true,
  },
  {
    _id: "course-help-colleague",
    title: "请同事帮忙",
    slug: "ask-colleague-help",
    description: "礼貌请求与回复感谢。",
    difficulty: "beginner",
    estimatedMinutes: 13,
    category: "协作",
    order: 4,
    isFeatured: false,
    isPublished: true,
  },
  {
    _id: "course-restaurant",
    title: "餐厅点餐",
    slug: "restaurant-ordering",
    description: "出差或日常就餐常见句子。",
    difficulty: "beginner",
    estimatedMinutes: 15,
    category: "生活",
    order: 5,
    isFeatured: false,
    isPublished: true,
  },
  {
    _id: "course-travel",
    title: "出差旅行",
    slug: "business-travel",
    description: "机场、酒店、交通的常用表达。",
    difficulty: "elementary",
    estimatedMinutes: 18,
    category: "旅行",
    order: 6,
    isFeatured: false,
    isPublished: true,
  },
];

export const seedSentences: Sentence[] = [
  { _id: "s1", courseSlug: "office-greeting", english: "Good morning. How are you?", chinese: "早上好，你怎么样？", pronunciationCn: "古德 摸宁。好啊 尤？", ipa: "/gʊd ˈmɔːrnɪŋ/ /haʊ ɑːr juː/", tags: ["greeting"], order: 1, isPublished: true },
  { _id: "s2", courseSlug: "office-greeting", english: "Nice to see you again.", chinese: "很高兴再次见到你。", pronunciationCn: "奈斯 吐 西 尤 额根。", ipa: "/naɪs tə siː juː əˈɡen/", tags: ["greeting"], order: 2, isPublished: true },
  { _id: "s3", courseSlug: "office-greeting", english: "How was your weekend?", chinese: "你周末过得怎么样？", pronunciationCn: "好 沃兹 尤儿 威肯德？", ipa: "/haʊ wəz jʊr ˈwiːkend/", tags: ["smalltalk"], order: 3, isPublished: true },
  { _id: "s4", courseSlug: "office-greeting", english: "Did you sleep well?", chinese: "你昨晚睡得好吗？", pronunciationCn: "迪德 尤 斯利普 威尔？", ipa: "/dɪd juː sliːp wel/", tags: ["smalltalk"], order: 4, isPublished: true },
  { _id: "s5", courseSlug: "office-greeting", english: "Let's have a great day.", chinese: "我们今天加油。", pronunciationCn: "莱次 海夫 额 格瑞特 得。", ipa: "/lets hæv ə ɡreɪt deɪ/", tags: ["encourage"], order: 5, isPublished: true },
  { _id: "s6", courseSlug: "office-greeting", english: "I will grab some coffee.", chinese: "我去拿点咖啡。", pronunciationCn: "艾 威尔 格瑞布 萨姆 咖啡。", ipa: "/aɪ wɪl ɡræb sʌm ˈkɔːfi/", tags: ["daily"], order: 6, isPublished: true },
  { _id: "s7", courseSlug: "office-greeting", english: "See you in the meeting room.", chinese: "会议室见。", pronunciationCn: "西 尤 因 则 密停 如姆。", ipa: "/siː juː ɪn ðə ˈmiːtɪŋ ruːm/", tags: ["meeting"], order: 7, isPublished: true },
  { _id: "s8", courseSlug: "office-greeting", english: "Have a productive morning.", chinese: "祝你上午高效。", pronunciationCn: "海夫 额 普若达科提夫 摸宁。", ipa: "/hæv ə prəˈdʌktɪv ˈmɔːrnɪŋ/", tags: ["work"], order: 8, isPublished: true },

  { _id: "s9", courseSlug: "self-introduction", english: "Hi, I'm Lily from the finance team.", chinese: "你好，我是财务组的 Lily。", pronunciationCn: "嗨，艾姆 莉莉 福肉姆 则 发奶恩斯 提姆。", ipa: "/haɪ aɪm ˈlɪli frəm ðə ˈfaɪnæns tiːm/", tags: ["intro"], order: 1, isPublished: true },
  { _id: "s10", courseSlug: "self-introduction", english: "I joined this company last month.", chinese: "我上个月加入这家公司。", pronunciationCn: "艾 角因德 迪斯 康帕尼 拉斯特 芒斯。", ipa: "/aɪ dʒɔɪnd ðɪs ˈkʌmpəni læst mʌnθ/", tags: ["intro"], order: 2, isPublished: true },
  { _id: "s11", courseSlug: "self-introduction", english: "My role is project coordinator.", chinese: "我的岗位是项目协调员。", pronunciationCn: "麦 柔哦 以兹 普若杰克特 口奥迪内特。", ipa: "/maɪ roʊl ɪz ˈprɑːdʒekt koʊˈɔːrdɪneɪtər/", tags: ["job"], order: 3, isPublished: true },
  { _id: "s12", courseSlug: "self-introduction", english: "I focus on schedule and communication.", chinese: "我主要负责进度和沟通。", pronunciationCn: "艾 佛口斯 昂 斯凯久 欧 安德 康缪尼凯神。", ipa: "/aɪ ˈfoʊkəs ɑːn ˈskedʒuːl ænd kəˌmjuːnɪˈkeɪʃən/", tags: ["job"], order: 4, isPublished: true },
  { _id: "s13", courseSlug: "self-introduction", english: "Please call me Lily.", chinese: "请叫我 Lily。", pronunciationCn: "普利兹 考我 莉莉。", ipa: "/pliːz kɔːl mi ˈlɪli/", tags: ["intro"], order: 5, isPublished: true },
  { _id: "s14", courseSlug: "self-introduction", english: "I am happy to work with you.", chinese: "很高兴和你一起工作。", pronunciationCn: "艾 艾姆 哈皮 吐 沃克 维兹 尤。", ipa: "/aɪ æm ˈhæpi tə wɜːrk wɪð juː/", tags: ["intro"], order: 6, isPublished: true },
  { _id: "s15", courseSlug: "self-introduction", english: "I can support data reports.", chinese: "我可以支持数据报表。", pronunciationCn: "艾 看 萨坡特 得特 报破次。", ipa: "/aɪ kən səˈpɔːrt ˈdeɪtə rɪˈpɔːrts/", tags: ["work"], order: 7, isPublished: true },
  { _id: "s16", courseSlug: "self-introduction", english: "Let's keep in touch.", chinese: "我们保持联系。", pronunciationCn: "莱次 凯普 因 塔吃。", ipa: "/lets kiːp ɪn tʌtʃ/", tags: ["closing"], order: 8, isPublished: true },

  { _id: "s17", courseSlug: "meeting-basics", english: "Let's start the meeting.", chinese: "我们开始开会吧。", pronunciationCn: "莱次 斯达特 则 密停。", ipa: "/lets stɑːrt ðə ˈmiːtɪŋ/", tags: ["meeting"], order: 1, isPublished: true },
  { _id: "s18", courseSlug: "meeting-basics", english: "Can everyone hear me?", chinese: "大家都能听到我吗？", pronunciationCn: "看 埃芙瑞万 希尔 米？", ipa: "/kæn ˈevriwʌn hɪr miː/", tags: ["meeting"], order: 2, isPublished: true },
  { _id: "s19", courseSlug: "meeting-basics", english: "Please share your update.", chinese: "请分享你的进展。", pronunciationCn: "普利兹 谢尔 尤儿 阿普得特。", ipa: "/pliːz ʃer jʊr ˈʌpdeɪt/", tags: ["update"], order: 3, isPublished: true },
  { _id: "s20", courseSlug: "meeting-basics", english: "I have one quick question.", chinese: "我有一个简短问题。", pronunciationCn: "艾 海夫 万 奎克 奎斯晨。", ipa: "/aɪ hæv wʌn kwɪk ˈkwestʃən/", tags: ["question"], order: 4, isPublished: true },
  { _id: "s21", courseSlug: "meeting-basics", english: "Could you repeat that?", chinese: "你可以再说一遍吗？", pronunciationCn: "库德 尤 瑞皮特 赞？", ipa: "/kʊd juː rɪˈpiːt ðæt/", tags: ["clarify"], order: 5, isPublished: true },
  { _id: "s22", courseSlug: "meeting-basics", english: "I agree with this point.", chinese: "我同意这个观点。", pronunciationCn: "艾 额格瑞 维兹 迪斯 坡因特。", ipa: "/aɪ əˈɡriː wɪð ðɪs pɔɪnt/", tags: ["opinion"], order: 6, isPublished: true },
  { _id: "s23", courseSlug: "meeting-basics", english: "Let's discuss this later.", chinese: "我们稍后再讨论这个。", pronunciationCn: "莱次 迪斯卡斯 迪斯 莱特。", ipa: "/lets dɪsˈkʌs ðɪs ˈleɪtər/", tags: ["meeting"], order: 7, isPublished: true },
  { _id: "s24", courseSlug: "meeting-basics", english: "Thanks, meeting is closed.", chinese: "谢谢，会议结束。", pronunciationCn: "三克斯，密停 以兹 克漏兹德。", ipa: "/θæŋks ˈmiːtɪŋ ɪz kloʊzd/", tags: ["closing"], order: 8, isPublished: true },

  { _id: "s25", courseSlug: "ask-colleague-help", english: "Could you help me with this file?", chinese: "你能帮我处理这个文件吗？", pronunciationCn: "库德 尤 海普 米 维兹 迪斯 发优？", ipa: "/kʊd juː help miː wɪð ðɪs faɪl/", tags: ["help"], order: 1, isPublished: true },
  { _id: "s26", courseSlug: "ask-colleague-help", english: "I need your advice.", chinese: "我需要你的建议。", pronunciationCn: "艾 尼德 尤儿 埃德外斯。", ipa: "/aɪ niːd jʊr ədˈvaɪs/", tags: ["help"], order: 2, isPublished: true },
  { _id: "s27", courseSlug: "ask-colleague-help", english: "Do you have five minutes?", chinese: "你有五分钟吗？", pronunciationCn: "杜 尤 海夫 发夫 米妮次？", ipa: "/duː juː hæv faɪv ˈmɪnɪts/", tags: ["help"], order: 3, isPublished: true },
  { _id: "s28", courseSlug: "ask-colleague-help", english: "Can we review it together?", chinese: "我们能一起看一下吗？", pronunciationCn: "看 维 瑞维尤 伊特 特盖则？", ipa: "/kæn wiː rɪˈvjuː ɪt təˈɡeðər/", tags: ["collab"], order: 4, isPublished: true },
  { _id: "s29", courseSlug: "ask-colleague-help", english: "Your feedback is very helpful.", chinese: "你的反馈非常有帮助。", pronunciationCn: "尤儿 费得拜克 以兹 维瑞 海普佛。", ipa: "/jʊr ˈfiːdbæk ɪz ˈveri ˈhelpfəl/", tags: ["thanks"], order: 5, isPublished: true },
  { _id: "s30", courseSlug: "ask-colleague-help", english: "Thank you for your support.", chinese: "谢谢你的支持。", pronunciationCn: "三克 尤 佛 尤儿 萨坡特。", ipa: "/θæŋk juː fɔːr jʊr səˈpɔːrt/", tags: ["thanks"], order: 6, isPublished: true },
  { _id: "s31", courseSlug: "ask-colleague-help", english: "I really appreciate it.", chinese: "我非常感谢。", pronunciationCn: "艾 瑞利 啊普瑞谢特 伊特。", ipa: "/aɪ ˈriːəli əˈpriːʃieɪt ɪt/", tags: ["thanks"], order: 7, isPublished: true },
  { _id: "s32", courseSlug: "ask-colleague-help", english: "Please let me know when you're free.", chinese: "你有空时请告诉我。", pronunciationCn: "普利兹 莱特 米 诺 温 尤儿 福瑞。", ipa: "/pliːz let miː noʊ wen jʊr friː/", tags: ["schedule"], order: 8, isPublished: true },

  { _id: "s33", courseSlug: "restaurant-ordering", english: "Could I see the menu, please?", chinese: "请给我看一下菜单好吗？", pronunciationCn: "库德 艾 西 则 曼纽 普利兹？", ipa: "/kʊd aɪ siː ðə ˈmenjuː pliːz/", tags: ["restaurant"], order: 1, isPublished: true },
  { _id: "s34", courseSlug: "restaurant-ordering", english: "I would like chicken salad.", chinese: "我想要鸡肉沙拉。", pronunciationCn: "艾 乌德 赖克 齐肯 萨勒德。", ipa: "/aɪ wʊd laɪk ˈtʃɪkɪn ˈsæləd/", tags: ["ordering"], order: 2, isPublished: true },
  { _id: "s35", courseSlug: "restaurant-ordering", english: "Can I have less ice?", chinese: "可以少放点冰吗？", pronunciationCn: "看 艾 海夫 莱斯 艾斯？", ipa: "/kæn aɪ hæv les aɪs/", tags: ["ordering"], order: 3, isPublished: true },
  { _id: "s36", courseSlug: "restaurant-ordering", english: "No spicy, please.", chinese: "请不要辣。", pronunciationCn: "诺 斯派西 普利兹。", ipa: "/noʊ ˈspaɪsi pliːz/", tags: ["ordering"], order: 4, isPublished: true },
  { _id: "s37", courseSlug: "restaurant-ordering", english: "Can I pay by card?", chinese: "我可以刷卡吗？", pronunciationCn: "看 艾 配 拜 卡德？", ipa: "/kæn aɪ peɪ baɪ kɑːrd/", tags: ["payment"], order: 5, isPublished: true },
  { _id: "s38", courseSlug: "restaurant-ordering", english: "Could you split the bill?", chinese: "可以分开结账吗？", pronunciationCn: "库德 尤 斯普利特 则 比尔？", ipa: "/kʊd juː splɪt ðə bɪl/", tags: ["payment"], order: 6, isPublished: true },
  { _id: "s39", courseSlug: "restaurant-ordering", english: "Everything tastes great.", chinese: "味道很好。", pronunciationCn: "埃弗瑞星 泰斯茨 格瑞特。", ipa: "/ˈevriθɪŋ teɪsts ɡreɪt/", tags: ["restaurant"], order: 7, isPublished: true },
  { _id: "s40", courseSlug: "restaurant-ordering", english: "Thank you, have a nice day.", chinese: "谢谢，祝你今天愉快。", pronunciationCn: "三克尤，海夫 额 奈斯 得。", ipa: "/θæŋk juː hæv ə naɪs deɪ/", tags: ["closing"], order: 8, isPublished: true },

  { _id: "s41", courseSlug: "business-travel", english: "Where is the check-in counter?", chinese: "值机柜台在哪里？", pronunciationCn: "维尔 以兹 则 切克因 康特？", ipa: "/wer ɪz ðə tʃek ɪn ˈkaʊntər/", tags: ["airport"], order: 1, isPublished: true },
  { _id: "s42", courseSlug: "business-travel", english: "I have a reservation under Wang.", chinese: "我用 Wang 的名字预订了。", pronunciationCn: "艾 海夫 额 瑞泽维神 安德 旺。", ipa: "/aɪ hæv ə ˌrezərˈveɪʃən ˈʌndər wɑːŋ/", tags: ["hotel"], order: 2, isPublished: true },
  { _id: "s43", courseSlug: "business-travel", english: "Could you call a taxi for me?", chinese: "你可以帮我叫出租车吗？", pronunciationCn: "库德 尤 考 额 塔克西 佛 米？", ipa: "/kʊd juː kɔːl ə ˈtæksi fɔːr miː/", tags: ["transport"], order: 3, isPublished: true },
  { _id: "s44", courseSlug: "business-travel", english: "How long is the ride?", chinese: "路程大概多久？", pronunciationCn: "好 朗 以兹 则 赖德？", ipa: "/haʊ lɔːŋ ɪz ðə raɪd/", tags: ["transport"], order: 4, isPublished: true },
  { _id: "s45", courseSlug: "business-travel", english: "I need a quiet room.", chinese: "我需要一个安静的房间。", pronunciationCn: "艾 尼德 额 奎尔特 如姆。", ipa: "/aɪ niːd ə ˈkwaɪət ruːm/", tags: ["hotel"], order: 5, isPublished: true },
  { _id: "s46", courseSlug: "business-travel", english: "What time is breakfast?", chinese: "早餐几点开始？", pronunciationCn: "沃特 泰姆 以兹 布瑞克法斯特？", ipa: "/wʌt taɪm ɪz ˈbrekfəst/", tags: ["hotel"], order: 6, isPublished: true },
  { _id: "s47", courseSlug: "business-travel", english: "Please print this document.", chinese: "请打印这份文件。", pronunciationCn: "普利兹 普润特 迪斯 多克优门特。", ipa: "/pliːz prɪnt ðɪs ˈdɑːkjumənt/", tags: ["work"], order: 7, isPublished: true },
  { _id: "s48", courseSlug: "business-travel", english: "My return flight is tomorrow.", chinese: "我明天返程。", pronunciationCn: "麦 瑞特恩 福来特 以兹 图猫肉。", ipa: "/maɪ rɪˈtɜːrn flaɪt ɪz təˈmɑːroʊ/", tags: ["airport"], order: 8, isPublished: true },
];
